SELECT * 
FROM (
SELECT EMP_ID,FYQ1M1,  FYQ1M2, FYQ1M3,    FYQ2M1,   FYQ2M2,   FYQ2M3,  FYQ3M1,   FYQ3M2,  FYQ3M3,  FYQ4M1, FYQ4M2, FYQ4M3, Total , CONNECT_BY_ISLEAF AS LEAF , LEVEL AS D  
FROM  
(SELECT * FROM (
SELECT  EMP_ID  , MANAGER_ID  ,SUM(FYQ1M1) FYQ1M1, SUM(FYQ1M2) FYQ1M2, SUM(FYQ1M3) FYQ1M3,  SUM(FYQ2M1) FYQ2M1, SUM(FYQ2M2) FYQ2M2, SUM(FYQ2M3) FYQ2M3,  SUM(FYQ3M1) FYQ3M1, SUM(FYQ3M2) FYQ3M2, SUM(FYQ3M3) FYQ3M3,  SUM(FYQ4M1) FYQ4M1, SUM(FYQ4M2) FYQ4M2, SUM(FYQ4M3) FYQ4M3 , SUM(FYQ1M1+FYQ1M2+FYQ1M3+FYQ2M1+FYQ2M2+FYQ2M3+FYQ3M1+FYQ3M2+FYQ3M3+FYQ4M1+FYQ4M2+FYQ4M3   )  As Total  FROM 
(
WITH pivot_data AS (

SELECT COALESCE(TABLE1.EMP_ID , TABLE2.EMP_ID) AS EMP_ID , MANAGER_ID  ,COALESCE(DURATION , 0) AS DURATION   ,  COALESCE(TABLE1.QTR, TABLE2.QTR) AS QTR
FROM (   ( select table1.EMP_ID, table1.MANAGER_ID , TO_CHAR(table2.n) as QTR
               from 
                ( SELECT EMP_ID , MANAGER_ID
				 FROM TT_EMPLOYEE
				 START WITH EMP_ID= :P7_MANAGER_ID
				 CONNECT BY MANAGER_ID= PRIOR EMP_ID  ) table1 
               cross join 
                 (select level n from dual connect by level <= 12) table2 )
  ) TABLE1  

FULL OUTER JOIN 
(
               SELECT  B.ATTENDEE_ID AS EMP_ID ,   SUM (EXTRACT(DAY FROM HOURS)*24 + EXTRACT ( HOUR FROM HOURS) + EXTRACT ( MINUTE FROM HOURS)/60 ) AS DURATION , QTR
				 FROM 
                                 (
                                 SELECT TRAINING_ID , SESSION_ID , 
                                        CASE 
										WHEN EXTRACT(month FROM  FROM_DATETIMEL)  IN (12) THEN '12'
										  WHEN EXTRACT(month FROM FROM_DATETIMEL) IN (11)  THEN '11'
										  WHEN EXTRACT(month FROM  FROM_DATETIMEL) IN (10) THEN '10'
										  WHEN EXTRACT(month FROM  FROM_DATETIMEL)  IN (9) THEN '9'
										  WHEN EXTRACT(month FROM  FROM_DATETIMEL) IN (8)  THEN '8'
										  WHEN EXTRACT(month FROM  FROM_DATETIMEL) IN (7) THEN '7'
										  WHEN EXTRACT(month FROM  FROM_DATETIMEL)  IN (6) THEN '6'
										  WHEN EXTRACT(month FROM  FROM_DATETIMEL) IN (5)  THEN '5'
										  WHEN EXTRACT(month FROM  FROM_DATETIMEL) IN (4) THEN '4'
										  WHEN EXTRACT(month FROM  FROM_DATETIMEL)  IN (3) THEN '3'
										  WHEN EXTRACT(month FROM  FROM_DATETIMEL) IN (2)  THEN '2'
										  ELSE '1'
                                        END As QTR ,EXTRACT (DAY FROM NUMBER_OF_DAYS) * INTERVAL AS HOURS
				 FROM TTEVENT_SESSIONS
                                 WHERE
                                  ( FROM_DATETIMEL between ADD_MONTHS(to_date('01-06-'|| :P30_YEAR ,'dd-mm-yyyy'),-12) and to_date('01-06-' || :P30_YEAR,'dd-mm-yyyy') )
                                 ) A ,

				 TTESESSIONS_ATTENDEE B ,

				 (
                                 SELECT EMP_ID 
				 FROM TT_EMPLOYEE
				 START WITH EMP_ID= :P7_MANAGER_ID
				 CONNECT BY MANAGER_ID= PRIOR EMP_ID 

				 ) C

				 WHERE
				 B.ATTENDEE_ID = C.EMP_ID
				 AND A.TRAINING_ID = B.TRAINING_ID 
				 AND A.SESSION_ID = B.SESSION_ID  
				 GROUP BY ATTENDEE_ID, QTR 
)  TABLE2
ON TABLE1.QTR= TABLE2.QTR AND
TABLE1.EMP_ID= TABLE2.EMP_ID
ORDER BY EMP_ID, QTR
)
  SELECT *
  FROM   pivot_data
  PIVOT (
   SUM(DURATION)	
   for QTR in (6 as "FYQ1M1"  ,7 as "FYQ1M2",8 as "FYQ1M3",9 as "FYQ2M1",10 as "FYQ2M2" ,11 as "FYQ2M3",12 as "FYQ3M1" ,1 as "FYQ3M2",2 as "FYQ3M3",3 as "FYQ4M1",4 as "FYQ4M2",5 as "FYQ4M3" )
))
 group by rollup (MANAGER_ID,EMP_ID ) 
) WHERE EMP_ID != 'TOTAL' )
CONNECT BY MANAGER_ID= PRIOR EMP_ID 
START WITH EMP_ID= :P7_MANAGER_ID )
WHERE LEAF=  1 and (:P8_SCOPE = 0 or D = 2);